In [3]:
%matplotlib notebook

from numpy import *
from scipy import signal
from scipy.signal import filter_design as fd
from matplotlib import pyplot as plt


In [4]:
# Specification for our filter
Wp = 0.270   # end of passband, normalized frequency
Ws = 0.412   # start of the stopband, normalized frequency 
Rp = 0.1     # passband maximum loss (gpass)
As = 60      # stopband min attenuation (gstop)

Filters = {'ellip' : (), 'cheby2' : ()}

# The ellip and cheby2 filter design
Filters['ellip'] = fd.iirdesign(Wp, Ws, Rp, As, ftype='ellip')
Filters['cheby2'] = fd.iirdesign(Wp, Ws, Rp, As, ftype='cheby2')

In [5]:
(w,H) = signal.freqz(*Filters['ellip'])

f, ax = plt.subplots()
ax.plot(w/pi*44100, 20*log10(abs(H)))
ax.set_title('Windowed Frequency Sampling (firwin) Impulse Response')
ax.grid(True)

<IPython.core.display.Javascript object>

In [25]:
signal.freqz([0.5, 0.5], [0,1], 10)

(array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
         1.57079633,  1.88495559,  2.19911486,  2.51327412,  2.82743339]),
 array([ 1.00000000+0.j        ,  0.97552826+0.1545085j ,
         0.90450850+0.29389263j,  0.79389263+0.4045085j ,
         0.65450850+0.47552826j,  0.50000000+0.5j       ,
         0.34549150+0.47552826j,  0.20610737+0.4045085j ,
         0.09549150+0.29389263j,  0.02447174+0.1545085j ]))

In [26]:
Filters['ellip'][0],Filters['ellip'][1]

(array([ 0.00685858,  0.00424427,  0.01363637,  0.00939893,  0.01363637,
         0.00424427,  0.00685858]),
 array([ 1.        , -3.6133816 ,  6.29949582, -6.44744259,  4.04658649,
        -1.4649745 ,  0.23927553]))

In [30]:
(w,H) = signal.freqz([0.5, 0.5], [1])

In [31]:
abs(H)

array([ 1.        ,  0.99999529,  0.99998118,  0.99995764,  0.9999247 ,
        0.99988235,  0.99983058,  0.99976941,  0.99969882,  0.99961882,
        0.99952942,  0.9994306 ,  0.99932238,  0.99920476,  0.99907773,
        0.99894129,  0.99879546,  0.99864022,  0.99847558,  0.99830154,
        0.99811811,  0.99792529,  0.99772307,  0.99751146,  0.99729046,
        0.99706007,  0.9968203 ,  0.99657115,  0.99631261,  0.9960447 ,
        0.99576741,  0.99548076,  0.99518473,  0.99487933,  0.99456457,
        0.99424045,  0.99390697,  0.99356414,  0.99321195,  0.99285041,
        0.99247953,  0.99209931,  0.99170975,  0.99131086,  0.99090264,
        0.99048508,  0.99005821,  0.98962202,  0.98917651,  0.98872169,
        0.98825757,  0.98778414,  0.98730142,  0.9868094 ,  0.9863081 ,
        0.98579751,  0.98527764,  0.9847485 ,  0.98421009,  0.98366242,
        0.98310549,  0.9825393 ,  0.98196387,  0.98137919,  0.98078528,
        0.98018214,  0.97956977,  0.97894818,  0.97831737,  0.97